-- AlterTable
ALTER TABLE "Config" ADD COLUMN     "EMAIL_FROM" TEXT,
ADD COLUMN     "EMAIL_PASS" TEXT,
ADD COLUMN     "EMAIL_USER" TEXT,
ADD COLUMN     "VNP_API_URL" TEXT,
ADD COLUMN     "VNP_SECRET" TEXT,
ADD COLUMN     "VNP_TMN_CODE" TEXT,
ADD COLUMN     "banner" JSONB;
